SELECT top 100
L_MAILITMS.MAILITM_FID AS Tracking,
L_MAILITM_CUSTOMERS.CUSTOMER_NAME AS [Nombre Destinatario],
L_MAILITM_CUSTOMERS.CUSTOMER_PHONE_NO AS [Numero de Telefono],
L_MAILITM_CUSTOMERS.CUSTOMER_ADDRESS AS Dirección,
L_MAILITMS.MAILITM_WEIGHT AS Peso,
C_MAIL_CLASSES.MAIL_CLASS_NM AS Categoria,
C_COUNTRIES.COUNTRY_NM AS [País Origen],
L_MAILITMS.CUSTOMS_NO AS [Citación/Entregado],
L_MAILITMS.EVT_GMT_DT AS [Fecha Evento],
L_MAILITMS.EVT_TYPE_CD,
N_OWN_OFFICES.OFFICE_NM AS [Oficina Destino],
L_MAILITMS.MISC1 AS Entregado,
C_EVENT_TYPES.EVENT_TYPE_NM AS Entregado
FROM L_MAILITMS
INNER JOIN C_MAIL_CLASSES ON L_MAILITMS.MAIL_CLASS_CD = C_MAIL_CLASSES.MAIL_CLASS_CD
INNER JOIN N_OWN_OFFICES ON L_MAILITMS.EVT_OFFICE_CD = N_OWN_OFFICES.OWN_OFFICE_CD
LEFT OUTER JOIN C_EVENT_TYPES ON L_MAILITMS.EVT_TYPE_CD = C_EVENT_TYPES.EVENT_TYPE_CD
LEFT OUTER JOIN C_COUNTRIES ON L_MAILITMS.ORIG_COUNTRY_CD = C_COUNTRIES.COUNTRY_CD
LEFT OUTER JOIN L_MAILITM_CUSTOMERS ON L_MAILITMS.MAILITM_PID = L_MAILITM_CUSTOMERS.MAILITM_PID