--restaurar script
--sqlcmd -S localhost -i c:/wwwroot/squemadatabaseschatbot.sql

--Tipos

USE [IPS5Db]
GO

-- Código de País (ISO 2 letras)
CREATE TYPE [dbo].[T_COUNTRY_CODE] FROM CHAR(2) NOT NULL;

GO
-- Nombres generales
CREATE TYPE [dbo].[T_NAME] FROM NVARCHAR(max) NOT NULL;
GO
-- Indicador de validez (booleano, 'Y' o 'N')
CREATE TYPE [dbo].[T_VALIDITY_IND] FROM NVARCHAR(max) NOT NULL;
GO
-- Coordenadas (flotantes para latitud/longitud)
CREATE TYPE [dbo].[T_COORDINATE] FROM FLOAT NULL;
GO
-- Fecha y hora
CREATE TYPE [dbo].[T_DATETIME] FROM DATETIME NULL;
GO
-- Tipo de evento (entero para códigos)
CREATE TYPE [dbo].[T_EVENT_TYPE_CODE] FROM INT NOT NULL;
GO
-- Código de tipo de unidad postal
CREATE TYPE [dbo].[T_MAILUNIT_TYPE_CODE] FROM NVARCHAR(max) NOT NULL;
GO
-- Identificador global único (GUID)
CREATE TYPE [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] FROM UNIQUEIDENTIFIER NOT NULL;
GO
-- Nombre de cliente largo
CREATE TYPE [dbo].[T_CUSTOMER_BIG_NAME] FROM NVARCHAR(200) NULL;
GO
-- Número de teléfono
CREATE TYPE [dbo].[T_TELEPHONE_NUMBER] FROM NVARCHAR(max) NULL;
GO
-- Dirección postal
CREATE TYPE [dbo].[T_POSTAL_ADDRESS] FROM NVARCHAR(255) NULL;
GO
-- Nombre de ciudad postal
CREATE TYPE [dbo].[T_POSTAL_CITY_NAME] FROM NVARCHAR(max) NULL;
GO
-- Código postal largo
CREATE TYPE [dbo].[T_BIG_POSTAL_POST_CODE] FROM NVARCHAR(max) NULL;
GO
-- Número de fax
CREATE TYPE [dbo].[T_FAX_NUMBER] FROM NVARCHAR(max) NULL;
GO
-- Dirección de correo electrónico
CREATE TYPE [dbo].[T_EMAIL_ADDR] FROM NVARCHAR(320) NULL;
GO
-- Código de clase de correo (una letra)
CREATE TYPE [dbo].[T_MAIL_CLASS_CODE] FROM NVARCHAR(max) NOT NULL;
GO
-- Indicador de estado completo (entero opcional)
CREATE TYPE [dbo].[T_STATE_INDICATOR_BIG_FULL_CODE] FROM INT NULL;
GO
-- Identificación completa del artículo postal
CREATE TYPE [dbo].[T_MAILITM_FULL_IDENTIFICATION] FROM NVARCHAR(max) NOT NULL;
GO
-- Peso del artículo postal
CREATE TYPE [dbo].[T_MAILITM_WEIGHT] FROM DECIMAL(8, 3) NULL;
GO
-- Código de moneda (ISO 4217, 3 letras)
CREATE TYPE [dbo].[T_CURRENCY_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Valor del artículo postal
CREATE TYPE [dbo].[T_MAILITM_VALUE] FROM DECIMAL(10, 2) NULL;
GO
-- Código de oficina propia
CREATE TYPE [dbo].[T_OWN_OFFICE_CD] FROM INT NOT NULL;
GO
-- Código de clasificación postal
CREATE TYPE [dbo].[T_SORTPLAN_CODE] FROM NVARCHAR(500) NULL;
GO
-- Tipo de país
CREATE TYPE [dbo].[T_COUNTRY_TYPE_CODE] FROM CHAR(2) NOT NULL;
GO
-- Código de clasificación de nivel bajo
CREATE TYPE [dbo].[T_SORTPLAN_LEVEL_LOW_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de clasificación de nivel alto
CREATE TYPE [dbo].[T_SORTPLAN_LEVEL_HIGH_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Indicador de bloqueo
CREATE TYPE [dbo].[T_BLOCK_IND] FROM NVARCHAR(max) NULL;
GO
-- Código de tipo de bloque
CREATE TYPE [dbo].[T_BLOCK_TYPE_CODE] FROM NVARCHAR(300) NULL;
GO
-- Código de zona postal
CREATE TYPE [dbo].[T_ZONE_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de tipo de zona postal
CREATE TYPE [dbo].[T_ZONE_TYPE_CODE] FROM NVARCHAR(max) NULL;
GO
-- Indicador de tipo de evento
CREATE TYPE [dbo].[T_EVTYPE_INBOTB_IND] FROM NVARCHAR(max) NOT NULL;
GO

-- Indicador booleano (Sí/No)
CREATE TYPE [dbo].[T_BOOL] FROM BIT NOT NULL;
GO
-- Indicador de pagador o remitente
CREATE TYPE [dbo].[T_SENDER_PAYEE_IND] FROM NVARCHAR(max) NOT NULL;
GO
-- Código de título
CREATE TYPE [dbo].[T_TITLE_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de método de notificación
CREATE TYPE [dbo].[T_NOTIFICATION_METHOD_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de tipo de identificación del cliente
CREATE TYPE [dbo].[T_CUSTOMER_ID_TYPE_CD] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Subentidad del país
CREATE TYPE [dbo].[T_COUNTRY_SUB_ENTITY] FROM NVARCHAR(max) NULL;
GO
-- Detalles del cliente
CREATE TYPE [dbo].[T_CUSTOMER_DETAILS] FROM NVARCHAR(MAX) NULL;
GO
-- Nombre corto
CREATE TYPE [dbo].[T_SHORT_NAME] FROM NVARCHAR(500) NOT NULL;
GO
-- Código clave de la lista
CREATE TYPE [dbo].[T_CODE_LIST_KEY_CD] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Código de origen del correo
CREATE TYPE [dbo].[T_MAIL_SOURCE_CODE] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Número de apartado postal
CREATE TYPE [dbo].[T_PO_BOX_NO] FROM NVARCHAR(MAX) NULL;
GO
-- Desplazamiento local (horario)
CREATE TYPE [dbo].[T_LOCAL_OFFSET] FROM INT NULL;
GO
-- Código de oficina propia
CREATE TYPE [dbo].[T_OWN_OFFICE_CD] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Identificador privado del usuario
CREATE TYPE [dbo].[T_USER_PRIVATE_IDENTIF] FROM NVARCHAR(500) NOT NULL;
GO
-- Identificador privado del taller
CREATE TYPE [dbo].[T_WKS_PRIVATE_IDENTIF] FROM NVARCHAR(500) NULL;
GO
-- Código de condición
CREATE TYPE [dbo].[T_CONDITION_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de motivo de retención
CREATE TYPE [dbo].[T_RETENTION_REASON_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de tipo de entrega
CREATE TYPE [dbo].[T_DELIVERY_TYPE_CODE] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Código de tipo de oficina de aduanas
CREATE TYPE [dbo].[T_CUSTOMS_OFFICE_TYPE_CODE] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Código de estado de liberación aduanera
CREATE TYPE [dbo].[T_CUSTOMS_RELEASE_STATUS_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Identificador local del artículo postal
CREATE TYPE [dbo].[T_MAILITM_LOCAL_IDENTIFIER] FROM NVARCHAR(max) NOT NULL;
GO
-- Código de clasificación aduanera
CREATE TYPE [dbo].[T_CUSTOMS_CLASSIFICATION_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Monto de impuestos
CREATE TYPE [dbo].[T_DUTIES_AMOUNT] FROM DECIMAL(10, 2) NULL;
GO
-- Número de aduana
CREATE TYPE [dbo].[T_CUSTOMS_NO] FROM NVARCHAR(max) NULL;
GO
-- Código de contenido del artículo postal
CREATE TYPE [dbo].[T_MAILITM_CONTENT_CODE] FROM NVARCHAR(MAX) NULL;
GO
-- Código de operador
CREATE TYPE [dbo].[T_OPERATOR_CODE] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Código de estado postal
CREATE TYPE [dbo].[T_POSTAL_STATUS_CODE] FROM NVARCHAR(MAX) NOT NULL;
GO
-- Código de tipo de producto
CREATE TYPE [dbo].[T_PRODUCT_TYPE_CD] FROM NVARCHAR(MAX) NULL;
GO
-- CGOampos misceláneos del artículo postal (16 caracteres)
CREATE TYPE [dbo].[T_MAILITM_MISC_16] FROM NVARCHAR(516) NULL;
GO
-- Campos misceláneos del artículo postal (64 caracteres)
CREATE TYPE [dbo].[T_MAILITM_MISC_64] FROM NVARCHAR(564) NULL;
GO
-- Comentarios de la unidad postal
CREATE TYPE [dbo].[T_MAILUNIT_COMMENTS] FROM NVARCHAR(255) NULL;
GO
-- Código completo de oficina propia
CREATE TYPE [dbo].[T_OWN_OFFICE_FULL_CODE] FROM NVARCHAR(max) NULL;
GO
-- Nombre del servidor de base de datos
CREATE TYPE [dbo].[T_DB_SERVER_NM] FROM NVARCHAR(500) NULL;
GO
-- Comentarios
CREATE TYPE [dbo].[T_COMMENTS] FROM NVARCHAR(MAX) NULL;
GO
-- Número de casa
CREATE TYPE [dbo].[T_HOUSE_NUMBER] FROM NVARCHAR(MAX) NULL;
GO
-- Código postal
CREATE TYPE [dbo].[T_POSTCODE] FROM NVARCHAR(MAX) NULL;
GO
-- T_BOOL
CREATE TYPE [dbo].[T_BOOL] FROM BIT NOT NULL;
GO
-- T_SENDER_PAYEE_IND
CREATE TYPE [dbo].[T_SENDER_PAYEE_IND] FROM CHAR(1) NOT NULL;
GO
-- T_LOCAL_OFFSET
CREATE TYPE [dbo].[T_LOCAL_OFFSET] FROM INT NULL;
GO
-- T_MAILITM_LOCAL_IDENTIFIER
CREATE TYPE [dbo].[T_MAILITM_LOCAL_IDENTIFIER] FROM NVARCHAR(40) NOT NULL;
GO
-- T_OWN_OFFICE_FULL_CODE
CREATE TYPE [dbo].[T_OWN_OFFICE_FULL_CODE] FROM NVARCHAR(20) NULL;
GO
-- Crear el tipo T_BOOL
IF NOT EXISTS (SELECT * FROM sys.types WHERE name = 'T_BOOL' AND is_user_defined = 1)
    CREATE TYPE [dbo].[T_BOOL] FROM BIT NOT NULL;
GO
-- Crear el tipo T_SENDER_PAYEE_IND
IF NOT EXISTS (SELECT * FROM sys.types WHERE name = 'T_SENDER_PAYEE_IND' AND is_user_defined = 1)
    CREATE TYPE [dbo].[T_SENDER_PAYEE_IND] FROM CHAR(1) NOT NULL;
GO
-- Crear el tipo T_LOCAL_OFFSET
IF NOT EXISTS (SELECT * FROM sys.types WHERE name = 'T_LOCAL_OFFSET' AND is_user_defined = 1)
    CREATE TYPE [dbo].[T_LOCAL_OFFSET] FROM INT NULL;
GO
-- Crear el tipo T_MAILITM_LOCAL_IDENTIFIER
IF NOT EXISTS (SELECT * FROM sys.types WHERE name = 'T_MAILITM_LOCAL_IDENTIFIER' AND is_user_defined = 1)
    CREATE TYPE [dbo].[T_MAILITM_LOCAL_IDENTIFIER] FROM NVARCHAR(40) NOT NULL;
GO
-- Crear el tipo T_OWN_OFFICE_FULL_CODE
IF NOT EXISTS (SELECT * FROM sys.types WHERE name = 'T_OWN_OFFICE_FULL_CODE' AND is_user_defined = 1)
    CREATE TYPE [dbo].[T_OWN_OFFICE_FULL_CODE] FROM NVARCHAR(20) NULL;

GO
CREATE TABLE [dbo].[C_COUNTRIES](
	[COUNTRY_CD] [dbo].[T_COUNTRY_CODE] NOT NULL,
	[COUNTRY_NM] [dbo].[T_NAME] NOT NULL,
	[VALID_IND] [dbo].[T_VALIDITY_IND] NOT NULL,
	[LATITUDE] [dbo].[T_COORDINATE] NULL,
	[LONGITUDE] [dbo].[T_COORDINATE] NULL,
	[EU_ENTRANCE_DT] [dbo].[T_DATETIME] NULL,
 CONSTRAINT [PK_C_COUNTRIES] PRIMARY KEY CLUSTERED 
(
	[COUNTRY_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[C_EVENT_TYPES]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[C_EVENT_TYPES](
	[EVENT_TYPE_CD] [dbo].[T_EVENT_TYPE_CODE] NOT NULL,
	[EVENT_TYPE_NM] [dbo].[T_NAME] NOT NULL,
	[MAILUNIT_TYPE_CD] [dbo].[T_MAILUNIT_TYPE_CODE] NOT NULL,
	[INB_OTB_IND] [dbo].[T_EVTYPE_INBOTB_IND] NOT NULL,
	[RESULT_STATE_IND_CD] [dbo].[T_STATE_INDICATOR_BIG_FULL_CODE] NULL,
	[PSD_EXPORT_FMT] [dbo].[T_NAME] NULL,
	[VALID_IND] [dbo].[T_VALIDITY_IND] NOT NULL,
	[STORE_ONLY_EVENT_ON_IMPORT] [dbo].[T_BOOL] NULL,
 CONSTRAINT [PK_C_EVENT_TYPES] PRIMARY KEY CLUSTERED 
(
	[EVENT_TYPE_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[C_MAIL_CLASSES]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[C_MAIL_CLASSES](
	[MAIL_CLASS_CD] [dbo].[T_MAIL_CLASS_CODE] NOT NULL,
	[MAIL_CLASS_NM] [dbo].[T_NAME] NOT NULL,
	[VALID_IND] [dbo].[T_VALIDITY_IND] NOT NULL) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[L_MAILITM_CUSTOMERS]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[L_MAILITM_CUSTOMERS](
	[MAILITM_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NOT NULL,
	[SENDER_PAYEE_IND] [dbo].[T_SENDER_PAYEE_IND] NOT NULL,
	[CUSTOMER_FCD] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[COUNTRY_CD] [dbo].[T_COUNTRY_CODE] NOT NULL,
	[TITLE_CD] [dbo].[T_TITLE_CODE] NOT NULL,
	[NOTIFICATION_METHOD_CD] [dbo].[T_NOTIFICATION_METHOD_CODE] NULL,
	[CUSTOMER_ID_TYPE_CD] [dbo].[T_CUSTOMER_ID_TYPE_CD] NULL,
	[CUSTOMER_NAME] [dbo].[T_CUSTOMER_BIG_NAME] NOT NULL,
	[CUSTOMER_FORENAME] [dbo].[T_CUSTOMER_BIG_NAME] NULL,
	[CUSTOMER_ADDRESS] [dbo].[T_POSTAL_ADDRESS] NULL,
	[CUSTOMER_CITY] [dbo].[T_POSTAL_CITY_NAME] NULL,
	[CUSTOMER_POST_CODE] [dbo].[T_BIG_POSTAL_POST_CODE] NULL,
	[CUSTOMER_PHONE_NO] [dbo].[T_TELEPHONE_NUMBER] NULL,
	[CUSTOMER_FAX_NO] [dbo].[T_FAX_NUMBER] NULL,
	[CUSTOMER_COUNTRY_SUB_ENTITY] [dbo].[T_COUNTRY_SUB_ENTITY] NULL,
	[CUSTOMER_EMAIL_ADDRESS] [dbo].[T_EMAIL_ADDR] NULL,
	[CUSTOMER_ID_NO] [varchar](20) NULL,
	[CUSTOMER_DETAILS] [dbo].[T_CUSTOMER_DETAILS] NULL,
	[STREET_NM] [nvarchar](64) NULL,
	[HOUSE_NO] [dbo].[T_SHORT_NAME] NULL,
	[HOUSE_NO_EXT] [dbo].[T_SHORT_NAME] NULL,
	[CUSTOMER_LANGUAGE] [nvarchar](3) SPARSE  NULL,
	[ALT_DELIV_ADDRESS_CITY_TOWN] [nvarchar](35) SPARSE  NULL,
	[ALT_DELIV_ADDRESS_HOUSE_ID] [varchar](30) SPARSE  NULL,
	[ALT_DELIV_ADDRESS_LINE_1] [nvarchar](100) SPARSE  NULL,
	[ALT_DELIV_ADDRESS_LINE_2] [nvarchar](100) SPARSE  NULL,
	[ALT_DELIV_ADDRESS_POSTCODE] [varchar](17) SPARSE  NULL,
	[COD_BIC] [varchar](11) SPARSE  NULL,
	[COD_IBAN] [varchar](34) SPARSE  NULL,
	[CONSUMER_REG_NUMBER] [varchar](35) SPARSE  NULL,
	[CHARG_ARRANGEMENT_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
	[ADDRESS_LINE_2] [nvarchar](100) SPARSE  NULL,
	[INTENDED_DELIVERY_LOCATION_TYPE_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
	[DELIVERY_SERVICE_TYPE_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
	[PICK_UP_POINT_ID] [varchar](35) SPARSE  NULL,
	[EXPORT_MAIL_SOURCE_CD] [dbo].[T_MAIL_SOURCE_CODE] SPARSE  NULL,
	[PO_BOX_NO] [dbo].[T_PO_BOX_NO] SPARSE  NULL,
	[POSTE_RESTANTE] [dbo].[T_BOOL] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[L_MAILITM_EVENTS]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[L_MAILITM_EVENTS](
	[MAILITM_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NOT NULL,
	[EVENT_TYPE_CD] [dbo].[T_EVENT_TYPE_CODE] NOT NULL,
	[EVENT_GMT_DT] [dbo].[T_DATETIME] NOT NULL,
	[CAPTURE_GMT_DT] [datetime2](7) NOT NULL,
	[EVENT_LOCAL_OFFSET] [dbo].[T_LOCAL_OFFSET] NOT NULL,
	[EVENT_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] NULL,
	[USER_PID] [dbo].[T_USER_PRIVATE_IDENTIF] NULL,
	[WORKSTATION_PID] [dbo].[T_WKS_PRIVATE_IDENTIF] NULL,
	[CONDITION_CD] [dbo].[T_CONDITION_CODE] NULL,
	[RETENTION_REASON_CD] [dbo].[T_RETENTION_REASON_CODE] NULL,
	[RECPTCL_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[INNRBAG_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[NEXT_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] NULL,
	[STATE_IND_CD] [dbo].[T_STATE_INDICATOR_BIG_FULL_CODE] NULL,
	[MAIL_SOURCE_CD] [dbo].[T_MAIL_SOURCE_CODE] SPARSE  NULL,
	[DELIVERY_TYPE_CD] [dbo].[T_DELIVERY_TYPE_CODE] SPARSE  NULL,
	[CUSTOMS_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] SPARSE  NULL,
	[CUSTOMS_OFFICE_TYPE_CD] [dbo].[T_CUSTOMS_OFFICE_TYPE_CODE] SPARSE  NULL,
	[CUSTOMS_RELEASE_STATUS_CD] [dbo].[T_CUSTOMS_RELEASE_STATUS_CODE] SPARSE  NULL,
	[ATTEMPTED_DELIVERY_LOCATION] [varchar](35) SPARSE  NULL,
	[LODGEMENT_MODE_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
	[TRANSIT_DIRECTION_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[L_MAILITMS]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[L_MAILITMS](
	[MAILITM_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NOT NULL,
	[MAILITM_FID] [dbo].[T_MAILITM_FULL_IDENTIFICATION] NOT NULL,
	[MAILITM_LOCAL_ID] [dbo].[T_MAILITM_LOCAL_IDENTIFIER] NULL,
	[MAILITM_WEIGHT] [dbo].[T_MAILITM_WEIGHT] NULL,
	[CURRENCY_CD] [dbo].[T_CURRENCY_CODE] NULL,
	[MAILITM_VALUE] [dbo].[T_MAILITM_VALUE] NULL,
	[DUTIABLE_IND] [dbo].[T_CUSTOMS_CLASSIFICATION_CODE] NULL,
	[DUTIES_AMOUNT] [dbo].[T_DUTIES_AMOUNT] NULL,
	[CUSTOMS_NO] [dbo].[T_CUSTOMS_NO] NULL,
	[MAIL_CLASS_CD] [dbo].[T_MAIL_CLASS_CODE] NOT NULL,
	[MAILITM_CONTENT_CD] [dbo].[T_MAILITM_CONTENT_CODE] NULL,
	[OPERATOR_CD] [dbo].[T_OPERATOR_CODE] NULL,
	[ORIG_COUNTRY_CD] [dbo].[T_COUNTRY_CODE] NOT NULL,
	[DEST_COUNTRY_CD] [dbo].[T_COUNTRY_CODE] NULL,
	[STATE_IND_CD] [dbo].[T_STATE_INDICATOR_BIG_FULL_CODE] NULL,
	[POSTAL_STATUS_CD] [dbo].[T_POSTAL_STATUS_CODE] NULL,
	[EVT_TYPE_CD] [dbo].[T_EVENT_TYPE_CODE] NULL,
	[EVT_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] NULL,
	[EVT_GMT_DT] [dbo].[T_DATETIME] NOT NULL,
	[EVT_INNRBAG_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[EVT_RECPTCL_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[PRODUCT_TYPE_CD] [dbo].[T_PRODUCT_TYPE_CD] NULL,
	[MISC1] [dbo].[T_MAILITM_MISC_16] NULL,
	[MISC2] [dbo].[T_MAILITM_MISC_16] NULL,
	[MISC3] [dbo].[T_MAILITM_MISC_64] NULL,
	[COMMENTS] [dbo].[T_MAILUNIT_COMMENTS] NULL,
	[POSTAGE_PAID_VALUE] [dbo].[T_MAILITM_VALUE] NULL,
	[POSTAGE_PAID_CURRENCY_CD] [dbo].[T_CURRENCY_CODE] NULL,
	[ADDITIONAL_FEES_VALUE] [dbo].[T_MAILITM_VALUE] NULL,
	[ADDITIONAL_FEES_CURRENCY_CD] [dbo].[T_CURRENCY_CODE] NULL,
	[CUSTOMS_TAX_PID] [dbo].[T_GLOBAL_UNIQUE_IDENTIFIER] NULL,
	[MISC4] [dbo].[T_MAILITM_MISC_64] NULL,
	[NETWORK_ENTRY_LOCATION_TYPE_CD] [dbo].[T_CODE_LIST_KEY_CD] SPARSE  NULL,
	[MRS_STATUS_CD] [char](1) NULL,
	[MRS_EXPIRATION_DATE] [date] NULL,
	[MRS_ORIGINAL_ID] [dbo].[T_MAILITM_FULL_IDENTIFICATION] NULL,
 CONSTRAINT [PK_L_MAILITMS] PRIMARY KEY CLUSTERED 
(
	[MAILITM_PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[N_OWN_OFFICES]    Script Date: 18/11/2024 10:46:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[N_OWN_OFFICES](
	[OWN_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] NOT NULL,
	[OFFICE_FCD] [dbo].[T_OWN_OFFICE_FULL_CODE] NOT NULL,
	[OFFICE_NM] [dbo].[T_NAME] NOT NULL,
	[DB_SERVER_NM] [dbo].[T_DB_SERVER_NM] NULL,
	[VALID_IND] [dbo].[T_VALIDITY_IND] NOT NULL,
	[PHONE_NO] [dbo].[T_TELEPHONE_NUMBER] NULL,
	[COMMENTS] [dbo].[T_COMMENTS] NULL,
	[HOUSE_NUMBER] [dbo].[T_HOUSE_NUMBER] SPARSE  NULL,
	[ADDRESS_LINE_1] [dbo].[T_POSTAL_ADDRESS] SPARSE  NULL,
	[ADDRESS_LINE_2] [dbo].[T_POSTAL_ADDRESS] SPARSE  NULL,
	[POSTCODE] [dbo].[T_POSTCODE] SPARSE  NULL,
	[CITY] [dbo].[T_POSTAL_CITY_NAME] SPARSE  NULL,
	[CUSTOMS_OFFICE_CD] [dbo].[T_OWN_OFFICE_CD] NULL,
	[CUSTOMS_OFFICE_TYPE_CD] [dbo].[T_CUSTOMS_OFFICE_TYPE_CODE] NULL,
 CONSTRAINT [PK_N_OWN_OFFICES] PRIMARY KEY CLUSTERED 
(
	[OWN_OFFICE_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]